name: 'decision_safe'
version: '1.0.0'
config-version: 2

profile: 'decision_safe'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  decision_safe:
    bronze:
      materialized: view
    audit:
      materialized: table
    contracts:
      materialized: table
    analytics:
      materialized: table
